Avoid CSRF
418sec/node-login pull request #2
Opened 2020-12-08 04:40 UTC by alromh87

### 📊 Metadata *

#### Bounty URL: https://www.huntr.dev/bounties/1-other-node-login/

### ⚙️ Description *

node-login is a template for quickly building login systems on top of Node.js & MongoDB. It is vulnerable to CSRF attacks in Update and Delete profile actions

### 💻 Technical Description *

Avoid CSRF by using csrf token using csurf 

### 🐛 Proof of Concept (PoC) *

1. Download and setup node-login
2. Go to http://localhost:3000/signup and create an account
3. Create payload and serve trough web
```
<html>
  
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="http://localhost:3000/home" method="POST">
      <input type="hidden" name="name" value="hacked" />
      <input type="hidden" name="email" value="hacked&#64;test&#46;com" />
      <input type="hidden" name="country" value="Afghanistan" />
      <input type="hidden" name="pass" value="hacked" />
      <input type="submit" value="Submit request" />
    </form>
  </body>
</html>
```
4. Open payload from same browser as logged in user and click on Submit button
5. User data has been tempered with
![Captura de pantalla de 2020-12-07 21-08-45](https://user-images.githubusercontent.com/7505980/101440782-300cb880-38dd-11eb-9574-04b8e1965dde.png)

### 🔥 Proof of Fix (PoF) *

After fix data is unafected as csrf token is requiered for post actions

![Captura de pantalla de 2020-12-07 21-44-07](https://user-images.githubusercontent.com/7505980/101440795-34d16c80-38dd-11eb-824a-c51b5410d253.png)

### 👍 User Acceptance Testing (UAT)

All functinality is unafected
![Captura de pantalla de 2020-12-07 21-44-31](https://user-images.githubusercontent.com/7505980/101440807-3d29a780-38dd-11eb-95d0-faf67f77601a.png)

2020-12-17 07:26 UTC, mzfr reviewed
Hey, The fix looks good but I just think that instead of showing the complete debug message there should be some small error that won't give away internal paths etc.

2020-12-17 16:03 UTC, alromh87 commented
@mzfr thanks for the comment, updated

2020-12-17 16:06 UTC, mzfr approved these changes
Looks good now

2020-12-17 17:49 UTC, Mik317 requested changes
Hi @alromh87 :smile:,
thanks for the great fix :+1: 

Could you add the protection also for the `Delete` action?

Cheers,
Mik

2021-01-14 04:26 UTC, alromh87 commented
Hello @Mik317 I think delete action is already taken care of, unless I'm missing another endpoint, you can try with this POC:

```
<html>
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="http://localhost:3000/delete" method="POST">
      <input type="submit" value="Submit request" />
    </form>
  </body>
</html>
```

And you should get:
![Captura de pantalla de 2021-01-13 22-26-24](https://user-images.githubusercontent.com/7505980/104544836-63ceb280-55ee-11eb-973c-c0b4522d9d81.png)


Let me know what you think

2021-01-14 06:28 UTC, merged

2021-01-14 06:28 UTC, huntr-helper commented
Congratulations alromh87 - your fix has been selected! 🎉

Thanks for being part of the community & helping secure the world's open source code.
If you have any questions, please respond in the comments section, or hit us up on Discord. Your bounty is on its way - keep hunting!

[Come join us on Discord](https://huntr.dev/discord)